Switched to vanilla values to stop movement from flagging anticheats
PrismarineJS/prismarine-physics pull request #112
Opened 2023-11-28 08:50 UTC by loldoob

The values in the current version flag some anticheats. I switched them to the values from MoveEntityWithHeading in EntityLivingBase.java. These values now emulate vanilla movement with 99.9999999793% accuracy.

2023-11-28 09:25 UTC, extremeheat reviewed
Listing

2023-11-28 09:25 UTC, extremeheat commented on index.js
> +        acceleration = attributeSpeed * (0.16277136 / (inertia * inertia * inertia))
This is the only actual change in this PR. The other changes have no effect, you can revert them. If there are errors in calculation, they are likely to be caused by 64-bit vs 32-bit float differences, and that's what Math.fround is supposed to fix.

2023-11-29 20:42 UTC, frej4189 commented
Very likely that these values differ between versions.

2023-11-29 20:56 UTC, rom1504 commented
How do you measure 99.9999999793 accuracy?

On Wed, Nov 29, 2023, 21:42 Frej Alexander Nielsen ***@***.***>
wrote:

> Very likely that these values differ between versions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PrismarineJS/prismarine-physics/pull/112#issuecomment-1832670400>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR437WQWLEJBVQHS3TFGOTYG6M3NAVCNFSM6AAAAAA75LW2CCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZSGY3TANBQGA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-11-30 19:15 UTC, loldoob commented
I measured the difference in speed values across many different situations and it was off by 0.0000000207. The difference somes from 32 bit to 64 bit conversions from floats to doubles.

2023-11-30 19:35 UTC, frej4189 requested changes

2023-11-30 19:35 UTC, frej4189 commented on index.js
> +        vel.y = 0.42 * ((blockBelow && blockBelow.type === honeyblockId) ? physics.honeyblockJumpSpeed : 1)
This change is incorrect. Current version is right.

See https://github.com/extremeheat/extracted_minecraft_data/blob/client1.19.3/client/net/minecraft/world/entity/LivingEntity.java#L2019 for reference.

2023-12-31 13:08 UTC, rom1504 commented
please fix

2025-01-24 22:17 UTC, closed without merging